singleQuote: false
trailingComma: all
semi: true
tabWidth: 4
embeddedLanguageFormatting: auto
endOfLine: lf
printWidth: 80
quoteProps: as-needed
arrowParens: avoid
singleAttributePerLine: false
useTabs: false
overrides:
  - files:
      - "*.json"
      - "*.jsonc"
    options:
      trailingComma: none
  - files:
      - "*.json"
      - "*.jsonc"
      - "*.html"
      - "*.css"
      - "*.yaml"
      - "*.yml"
    options:
      tabWidth: 2
